import { Metadata } from 'next';
import { TodoDataType } from '~/types';

async function getData() {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos', {
    next: { revalidate: 10 },
  });
  if (!res.ok) {
    throw new Error('Failed to fetch data');
  }
  return res.json();
}
export const metadata: Metadata = {
  title: 'Avion About Page',
  description: 'Generated by create next app',
};

const About = async () => {
  const data: TodoDataType[] = await getData();

  return (
    <div>
      {data.map((el) => (
        <p key={el.id}> {el.title}</p>
      ))}
    </div>
  );
};

export default About;
