import type { Metadata } from 'next';
import { Gilda_Display } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import QueryContextProvider from '~/context';
import Header from '~/components/header';
import './globals.css';
import Navbar from '~/components/navbar';

const roboto = Gilda_Display({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <QueryContextProvider>
          <Header />
          <Navbar/>
          <NextTopLoader showSpinner={false} />
          {children}

        </QueryContextProvider>
      </body>
    </html>
  );
}
